### ISSUE TITLE
Fix module.json so it can be loaded on Foundry v11

### ISSUE THREAD

**Issue by kaelad02** [Benjaneer/storyteller-addon-singlesheet#2]
I was helping someone on Discord manually install this module on Foundry v11. It needs some changes to the `module.json` file in order to work with v11. I can't say whether that's all that's necessary to make it work in v11, but at least you can install/enable the module with this change.

1. The `authors` property needs to be changed from an array of strings to array of objects. It should be:
```json
  "authors": [
    {"name": "Benjaneer"}
  ],
```
2. The `compatibility` section lists the `maximum` version as `"10"`, which obviously won't work with v11. Unless you know it won't work with a higher version, I'd use `verified` instead of `maximum` here.
```json
  "compatibility": {
    "minimum": "10",
    "verified": "11"
  },
```

**Comment by Benjaneer** [comment]
I'm still using v10, please let me know if that works for v11

**Comment by kaelad02** [comment]
Yes, the changes I suggested will still work with v10. It'll be compatible with both v10 and v11.

**Comment by Benjaneer** [comment]
I mean that I made the changes, please validate.
(instead of verified 11 I removed the maximum, and updated the authors per your specification)

**Comment by kaelad02** [comment]
I was able to install and enable v1.2.2 of the module just fine on both my v10 and v11 setups. Thanks for fixing it so people can use it on v11.
